### PR TITLE
Add Method Values

### PR DESCRIPTION
**Pull request by eduhcastro**
❤️

### CODE REVIEW

**Comment by UziTech** [comment]
Can you explain why this is needed?

**Comment by eduhcastro** [comment]
> Can you explain why this is needed?

When I tried to use the tool, it said that this method did not exist (Values) so I created it.

__Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'InputBox' does not contain a definition for 'Values' and no accessible extension method 'Values' accepting a first argument of type 'InputBox' could be found (are you missing a using directive or an assembly reference?)_

**Comment by UziTech** [comment]
Why did you try using that method instead of the way that is shown in the docs?

**Comment by UziTech** [comment]
I see the issue. `Values` had been changed to `Items` and I forgot to update the docs. The example in the readme should work now.

Thanks for bringing this to my attention :100:

**Pull request closed without merging**
